### ISSUE TITLE
label 'number of simulations" et "nombre de cores" manquants

### ISSUE THREAD

**Issue by MaryemT** [avalanche-org/Gen_Assoc#30]
Lorqu'on choisit empirical analysis, une box s'ouvre mais le label choisir le nombre de simulations n'est pas présent. Ni celui pour choisir le nombre de cores

Si tu pouvais aussi mettre un saut de ligne entre les deux paramètres dans la box ce serait bien. 
Augmenter aussi la police d'ecriture

**Comment by Jukoo** [comment]
Everything  looks good on my browser  (Firefox)    
what kind of browser are you using ?  @MaryemT

**Comment by MaryemT** [comment]
Im using chrome
