### ISSUE TITLE
Run Analysis  was interrupted  after you made changes :construction:

### ISSUE THREAD

**Issue by Jukoo** [avalanche-org/Gen_Assoc#39]
-- Pedigree file : /home/umar/Desktop/Sanbox/Gen_Assoc/apps/vtmp/test/25markers.ped
 -- Map file : /home/umar/Desktop/Sanbox/Gen_Assoc/apps/vtmp/test/25markers.map
 -- Phenotype file : /home/umar/Desktop/Sanbox/Gen_Assoc/apps/vtmp/test/25markers.phen
 -- Selected phenotype : column 1
 -- Number of cores for analysis : 3
 -- Genotype Inference option selected 

 [] Reading ped, map, phen files...	FAILLURE : 1

**Comment by MaryemT** [comment]
Return to the older version
